/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Graficos;


import Graficos.RegistroDeExamenes.RegistrarExamen;
import ausentismo.ExamenDeIngreso;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Seguimiento_Casos extends javax.swing.JInternalFrame {

    private ausentismo.PanelFondo fondoMenu = null;
    private DefaultTableModel modeloTabla = null;
    private ArrayList<String[]> datosTabla;
    private  ArrayList<ExamenDeIngreso> ExamenesIngreso;
   
    public Seguimiento_Casos() {
        initComponents();
        fondoMenu = new ausentismo.PanelFondo();
        ausentismo.GraphicsAdmin.fondoAPanel(jPanel3, "src//Imagenes//fondo.gif", fondoMenu);
        jPanel3.setSize(this.getSize());
        fondoMenu.setSize(jPanel3.getSize());
        datosTabla = BaseDatos.Seguimiento_BD.datosTablaSeguimiento();
        inicializarTablaCasos();
        grupoTipo.add(radioButtonEI);
        grupoTipo.add(radioButtonCasos);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCasos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textBuscarCC = new javax.swing.JTextField();
        btnNuevoSeguimiento1 = new javax.swing.JButton();
        radioButtonCasos = new javax.swing.JRadioButton();
        radioButtonEI = new javax.swing.JRadioButton();
        btnBuscar1 = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jScrollPane1.setOpaque(false);

        TablaCasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Cedula", "Nombre", "Estado", "Diagnostico"
            }
        ));
        TablaCasos.setOpaque(false);
        jScrollPane1.setViewportView(TablaCasos);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/View.gif"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/List.gif"))); // NOI18N
        jButton6.setText("MOSTRAR CASO");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("CEDULA");

        btnNuevoSeguimiento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarCaso.png"))); // NOI18N
        btnNuevoSeguimiento1.setText("CERRAR CASO");
        btnNuevoSeguimiento1.setBorder(null);
        btnNuevoSeguimiento1.setBorderPainted(false);
        btnNuevoSeguimiento1.setContentAreaFilled(false);
        btnNuevoSeguimiento1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoSeguimiento1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoSeguimiento1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoSeguimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoSeguimiento1ActionPerformed(evt);
            }
        });

        radioButtonCasos.setBackground(new java.awt.Color(183, 240, 240));
        radioButtonCasos.setSelected(true);
        radioButtonCasos.setText("Casos");
        radioButtonCasos.setContentAreaFilled(false);
        radioButtonCasos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonCasosItemStateChanged(evt);
            }
        });
        radioButtonCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCasosActionPerformed(evt);
            }
        });

        radioButtonEI.setBackground(new java.awt.Color(183, 240, 240));
        radioButtonEI.setText("Exámenes de Ingreso");
        radioButtonEI.setContentAreaFilled(false);

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar.png"))); // NOI18N
        btnBuscar1.setText("Registrar");
        btnBuscar1.setBorder(null);
        btnBuscar1.setBorderPainted(false);
        btnBuscar1.setContentAreaFilled(false);
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNuevoSeguimiento1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBuscarCC, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar1)
                        .addGap(92, 92, 92)
                        .addComponent(radioButtonCasos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioButtonEI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButtonCasos)
                            .addComponent(radioButtonEI))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textBuscarCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(12, 12, 12)))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoSeguimiento1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jPanel3.setSize(this.getSize());
        fondoMenu.setSize(jPanel3.getSize());
    }//GEN-LAST:event_formComponentResized

    private void btnNuevoSeguimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoSeguimiento1ActionPerformed
        if(TablaCasos.getSelectedRow()>=0){ //Se comprueba que se haya seleccionado algun item de la tabla
            String id_Seguimiento = datosTabla.get(TablaCasos.getSelectedRow())[0];
            String estado = datosTabla.get(TablaCasos.getSelectedRow())[4];
            System.out.println("ESTADOOOOOO "+estado);
            if(estado.toUpperCase().equals("ABIERTO")){ // Se comprueba que el caso que se va a cerrar se encuentre abierto
                BaseDatos.Seguimiento_BD.cerrarCaso(id_Seguimiento);
                inicializarTablaCasos();
                datosTabla.get(TablaCasos.getSelectedRow())[4] = "CERRADO";
            }else{
                JOptionPane.showMessageDialog(null, "No puede cerrar un caso que ya se encuentra cerrado.","CASO CERRADO",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un caso a cerrar","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnNuevoSeguimiento1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int index = TablaCasos.getSelectedRow();
        if(index>=0){
            if(index < this.datosTabla.size()){

                Caso ventana = new Caso(null,true);
                ventana.setLocationRelativeTo(null);  
                if(radioButtonCasos.isSelected()){
                    ventana.setDatosIniciales(this.datosTabla.get(index));
                    
                }else{
                    ventana.setDatosInicialesEI(convEItoString(this.ExamenesIngreso.get(index)));
                    
                }
                ventana.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Por favor seleccione un registro que contenga datos.", "Error!!!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un caso de la tabla.", "Error!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    private String[] convEItoString(ExamenDeIngreso EI){
        String[] datos;
        datos = new String[9];
        datos[0]=EI.getID_Examen(); 
        datos[1]=EI.getFecha_Registro().toString();
        datos[2]=EI.getCC();
        datos[3]=EI.getNombre();
        datos[4]="ABIERTO";
        datos[5]=EI.getDiagnostico();
        datos[6]="";
        datos[7]=EI.getApellido();
        datos[8]="1";
        return datos;
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String CC = textBuscarCC.getText();
        if(radioButtonCasos.isSelected()){
           this.datosTabla = BaseDatos.Seguimiento_BD.obtenerCasosDe(CC);
           inicializarTablaCasos();
        }else{
            ArrayList<ExamenDeIngreso> Examenes = BaseDatos.Seguimiento_BD.obtenerExamenesDeIngresoDe(CC);
            this.ExamenesIngreso = Examenes;
            inicializarTablaEI();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void radioButtonCasosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonCasosItemStateChanged
        if(radioButtonCasos.isSelected()){ //En caso de que se desee ver los casos
            inicializarTablaCasos();
        }
        else{ 
            ArrayList<ausentismo.ExamenDeIngreso> ExIngreso = BaseDatos.Seguimiento_BD.obtenerExamenesDeIngreso();
            this.ExamenesIngreso = ExIngreso;
            inicializarTablaEI();
        }
    }//GEN-LAST:event_radioButtonCasosItemStateChanged

    private void radioButtonCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCasosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonCasosActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        RegistrarExamen re = new RegistrarExamen(null,true);
        re.setLocationRelativeTo(null);
        re.setVisible(true);
    }//GEN-LAST:event_btnBuscar1ActionPerformed
    /**
     * Este método se usa para llenar la tabla en seguimiento con los examenes
     * médicos de ingreso
     */
    private void inicializarTablaEI(){
        ArrayList<ausentismo.ExamenDeIngreso> ExIngreso = this.ExamenesIngreso;
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("FECHA REGISTRO");
        modeloTabla.addColumn("CEDULA");
        modeloTabla.addColumn("NOMBRE");
        modeloTabla.addColumn("APELLIDOS");
        //modeloTabla.addColumn("ESTADO");
        modeloTabla.addColumn("DIAGNOSTICO");
        Object[] iniciar = {"","","","",""};
        int tam = (ExIngreso.size()<28)? 28 : ExIngreso.size();
        for (int i = 0; i < tam; i++) {
            if(i<ExIngreso.size()){                
                ausentismo.ExamenDeIngreso E = ExIngreso.get(i);
                Object[] datosTabla = {E.getFecha_Registro(),E.getCC(),E.getNombre(),E.getApellido(),E.getDiagnostico()};
                modeloTabla.addRow(datosTabla);
            }else{
                modeloTabla.addRow(iniciar);
            }
        }
        TablaCasos.setModel(modeloTabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCasos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnNuevoSeguimiento1;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioButtonCasos;
    private javax.swing.JRadioButton radioButtonEI;
    private javax.swing.JTextField textBuscarCC;
    // End of variables declaration//GEN-END:variables

    private void inicializarTablaCasos(){
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("FECHA REGISTRO");
        modeloTabla.addColumn("CEDULA");
        modeloTabla.addColumn("NOMBRE");
        modeloTabla.addColumn("ESTADO");
        modeloTabla.addColumn("DIAGNOSTICO");
        Object[] iniciar = {"","","","",""};
        int tam = (this.datosTabla.size()<28)? 28 : this.datosTabla.size();
        for (int i = 0; i < tam; i++) {
            if(i<this.datosTabla.size()){
                String[] datos = this.datosTabla.get(i);
                Object[] datosTabla = {datos[1],datos[2],datos[3],datos[4],datos[5]};
                modeloTabla.addRow(datosTabla);
            }else{
                modeloTabla.addRow(iniciar);
            }
        }
        TablaCasos.setModel(modeloTabla);
    }
}
