/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Graficos.Filtros;

import com.toedter.calendar.JDateChooser;

/**
 *
 * @author usuario
 */
public class FiltroDemografia extends javax.swing.JDialog {

    /**
     * Creates new form FiltroDemografia
     */
    public FiltroDemografia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        FiltroSexo.add(sexoFiltroF);
        FiltroSexo.add(sexoFiltroM);
        FiltroSexo.add(sexoSinFiltro);
        iniciarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FiltroSexo = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sexoSinFiltro = new javax.swing.JRadioButton();
        comboNombre = new javax.swing.JComboBox();
        textNombre = new javax.swing.JTextField();
        comboFechaIngreso = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        spinnerPersonasACargo = new javax.swing.JSpinner();
        comboEps = new javax.swing.JComboBox();
        textEps = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboAFP = new javax.swing.JComboBox();
        textAFP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboPersonasACargo = new javax.swing.JComboBox();
        panelFechaIngreso = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        FechaIngreso2 = new com.toedter.calendar.JDateChooser();
        FechaIngreso1 = new com.toedter.calendar.JDateChooser();
        sexoFiltroF = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        sexoFiltroM = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jLabel6);

        jPanel1.setBackground(new java.awt.Color(183, 240, 240));

        jLabel1.setText("NOMBRE");

        jLabel2.setText("SEXO");

        sexoSinFiltro.setText("Sin Filtro");
        sexoSinFiltro.setOpaque(false);

        comboNombre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Filtro", "Igual a" }));
        comboNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNombreItemStateChanged(evt);
            }
        });

        comboFechaIngreso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Filtro", "=", "<", ">", "<=", ">=", "Entre" }));
        comboFechaIngreso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFechaIngresoItemStateChanged(evt);
            }
        });

        jLabel10.setText("FECHA DE INGRESO");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Filtro", "Area 1", "Area 2", "Area 3", "Area 4" }));

        jLabel9.setText("AREA");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Filtro", "Primaria", "Secundaria", "Técnico", "Tecnologo", "Pregrado", "Posgrado", "Maestria", "Doctorado", "Ningun tipo de Educacion" }));

        jLabel8.setText("EDUCACIÓN");

        jLabel7.setText("ESTADO CIVIL");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Filtro", "Soltero", "Casado", "Divorsiado", "Union Libre", "Viudo" }));

        comboEps.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Filtro", "Igual a" }));
        comboEps.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEpsItemStateChanged(evt);
            }
        });

        jLabel4.setText("AFP");

        comboAFP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Filtro", "Igual a" }));
        comboAFP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAFPItemStateChanged(evt);
            }
        });

        jLabel5.setText("PERSONAS A CARGO");

        comboPersonasACargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Filtro", "=", ">", "<", ">=", "<=" }));
        comboPersonasACargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPersonasACargoItemStateChanged(evt);
            }
        });

        panelFechaIngreso.setOpaque(false);

        jLabel11.setText("Y");

        javax.swing.GroupLayout panelFechaIngresoLayout = new javax.swing.GroupLayout(panelFechaIngreso);
        panelFechaIngreso.setLayout(panelFechaIngresoLayout);
        panelFechaIngresoLayout.setHorizontalGroup(
            panelFechaIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaIngresoLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(FechaIngreso2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelFechaIngresoLayout.setVerticalGroup(
            panelFechaIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaIngresoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFechaIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FechaIngreso2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sexoFiltroF.setText("F");
        sexoFiltroF.setOpaque(false);

        jLabel3.setText("EPS");

        sexoFiltroM.setText("M");
        sexoFiltroM.setOpaque(false);

        jButton1.setText("BUSCAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboAFP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textAFP, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexoSinFiltro))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sexoFiltroF)
                                        .addGap(18, 18, 18)
                                        .addComponent(sexoFiltroM))
                                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboEps, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textEps, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboPersonasACargo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerPersonasACargo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(comboFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FechaIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(panelFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sexoSinFiltro)
                    .addComponent(sexoFiltroF)
                    .addComponent(sexoFiltroM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboAFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboPersonasACargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerPersonasACargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(comboFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FechaIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNombreItemStateChanged
        checkStringFilter(comboNombre,textNombre);
    }//GEN-LAST:event_comboNombreItemStateChanged

    private void comboEpsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEpsItemStateChanged
        checkStringFilter(comboEps,textEps);
        
    }//GEN-LAST:event_comboEpsItemStateChanged

    private void comboPersonasACargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPersonasACargoItemStateChanged
        checkIntFilter(comboPersonasACargo, spinnerPersonasACargo);
    }//GEN-LAST:event_comboPersonasACargoItemStateChanged

    private void comboFechaIngresoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFechaIngresoItemStateChanged
        checkDateFilter(comboFechaIngreso, FechaIngreso1, panelFechaIngreso);
    }//GEN-LAST:event_comboFechaIngresoItemStateChanged

    private void comboAFPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAFPItemStateChanged
        checkStringFilter(comboAFP, textAFP);
    }//GEN-LAST:event_comboAFPItemStateChanged
    
    private void checkIntFilter(javax.swing.JComboBox combo,javax.swing.JSpinner num){
        if(combo.getSelectedIndex() == 0){
            num.setEnabled(false);
        }else{
            num.setEnabled(true);
        }
    }
    private void checkDateFilter(javax.swing.JComboBox combo,JDateChooser fecha1, javax.swing.JPanel panelFecha){
        String seleccion = combo.getSelectedItem().toString();
        if(combo.getSelectedIndex() == 0){
            fecha1.setEnabled(false);
            panelFecha.setVisible(false);
        }
        else if(seleccion.equals("Entre")){
            fecha1.setEnabled(true);
            panelFecha.setVisible(true);
        }
        else{
            fecha1.setEnabled(true);
            panelFecha.setVisible(false);
        }
        
    }
    
    /*
        FUNCION PARA ACTIVAR O DESACTIVAR LOS TEXTFIELDS DE LOS FILTROS QUE SON STRING
            SOLO SE PUEDEN COMPARAR SI SON IGUAL A OTRO STRING
    */
    private void checkStringFilter(javax.swing.JComboBox combo, javax.swing.JTextField text){
        int sinFiltro = 0;
        
        int seleccion = combo.getSelectedIndex();
        if(seleccion == sinFiltro){
            text.setEnabled(false);
        }
        else{
            text.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltroDemografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltroDemografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltroDemografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltroDemografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FiltroDemografia dialog = new FiltroDemografia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaIngreso1;
    private com.toedter.calendar.JDateChooser FechaIngreso2;
    private javax.swing.ButtonGroup FiltroSexo;
    private javax.swing.JComboBox comboAFP;
    private javax.swing.JComboBox comboEps;
    private javax.swing.JComboBox comboFechaIngreso;
    private javax.swing.JComboBox comboNombre;
    private javax.swing.JComboBox comboPersonasACargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelFechaIngreso;
    private javax.swing.JRadioButton sexoFiltroF;
    private javax.swing.JRadioButton sexoFiltroM;
    private javax.swing.JRadioButton sexoSinFiltro;
    private javax.swing.JSpinner spinnerPersonasACargo;
    private javax.swing.JTextField textAFP;
    private javax.swing.JTextField textEps;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables

    private void iniciarCampos(){
        textEps.setEnabled(false);
        textNombre.setEnabled(false);
        textAFP.setEnabled(false);
        spinnerPersonasACargo.setEnabled(false);
        panelFechaIngreso.setVisible(false);
        FechaIngreso1.setEnabled(false);
        
    }
}
